### PR TITLE
thursday testing

### PR DESCRIPTION
**Pull request by Robro1878**

### CODE REVIEW

**Review by crephoto — COMMENTED** [review]
Ks, Kv, Ka, and Kg belong in ArmTunable

**Review by crephoto — COMMENTED** [review]
Why are all kXXXNodePosition constants set to zero?

**Comment by RPellowski** [comment]
Ks, Kv, Ka, and Kg are sysId parameters, not tunable

**Comment by RPellowski** [comment]
All angle and position constants need to be calibrated

**Pull request merged**
